name: Update README with latest blog posts

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://pcodesdev.hashnode.dev/rss.xml"
          max_post_count: 5
          template: "[$title]($url) - $date"
          commit_message: "Updated README with the latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
